name: Run Pytest

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
      - feature/*  # Runs on pushes to any feature branch
  pull_request:
    branches:
      - main  # Runs for PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version (e.g., 3.8, 3.9)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt  # If you have a requirements file

    - name: Run tests
      run: |
        pytest
